# Use an official Nginx image
FROM nginx:alpine

# Copy the index.html file to the Nginx container
COPY index.html /usr/share/nginx/html/index.html

# Expose port 80 for your frontend service (default HTTP port)
EXPOSE 80

