apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-a
spec:
  replicas: 2  # 2 replicas of Backend A
  selector:
    matchLabels:
      app: backend-a
  template:
    metadata:
      labels:
        app: backend-a
    spec:
      containers:
      - name: backend-a
        image: backend-a:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: backend-a
spec:
  selector:
    app: backend-a
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: ClusterIP

