apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-b
spec:
  replicas: 2  # 2 replicas of Backend B
  selector:
    matchLabels:
      app: backend-b
  template:
    metadata:
      labels:
        app: backend-b
    spec:
      containers:
      - name: backend-b
        image: backend-b:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5002
        env:
        - name: OTEL_SERVICE_NAME
          value: "backend-b"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otel-collector.default.svc:4318"
        - name: OTEL_TRACES_EXPORTER
          value: "otlp"
        - name: OTEL_METRICS_EXPORTER
          value: "otlp"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "service.version=1.0.0,deployment.environment=dev"
        - name: OTEL_TRACES_SAMPLER
          value: "parentbased_traceidratio"
        - name: OTEL_TRACES_SAMPLER_ARG
          value: "0.2"
        command: ["opentelemetry-instrument"]
        args: ["python", "timecheck.py"]
---
apiVersion: v1
kind: Service
metadata:
  name: backend-b
spec:
  selector:
    app: backend-b
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
  type: ClusterIP

