apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-b
spec:
  replicas: 2  # 2 replicas of Backend B
  selector:
    matchLabels:
      app: backend-b
  template:
    metadata:
      labels:
        app: backend-b
    spec:
      containers:
      - name: backend-b
        image: backend-b:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: backend-b
spec:
  selector:
    app: backend-b
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
  type: ClusterIP

